# Generated by Django 4.2.7 on 2023-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="actual_return",
            field=models.DateField(blank=True, null=True),
        ),
    ]
