# Generated by Django 4.2.7 on 2023-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_notification",
            field=models.CharField(
                choices=[("email", "email"), ("telegram", "telegram")],
                default="email",
                max_length=25,
            ),
        ),
    ]
