# Generated by Django 4.2.7 on 2023-11-29 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_user_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_notification",
            new_name="notification",
        ),
    ]
